import { GuildImageType } from "@src/components/guild/GuildImage";

export interface GuildType {
  name: string;
  level: number;
  personCount: number;
  discription: string;
  guildImage: GuildImageType | null;
}

export interface GuildDetailType extends GuildType {
  guildMaster: string;
  guildSubMaster: string;
  guildMember: string[];
  createdAt: string;
  rank: number;
  condition: string;
  contact: string;
}

export const GUILD: GuildDetailType[] = [
  {
    name: "아무개",
    level: 12,
    personCount: 7,
    discription: "아무나 들어와서 즐기는 클랜이에용 레벨 제한 없습니다.",
    guildImage: null,
    guildMaster: "Tetromino_04",
    guildSubMaster: "daedyu",
    guildMember: [
      "jbj338033",
      "cher1shrxd",
      "bestdevmgp",
      "choijangwoo",
      "bluechaani",
    ],
    createdAt: "2025. 09. 23.",
    rank: 99,
    condition: "무관",
    contact: "디스코드 : https://discord.gg/3cDfDtgQEg",
  },
  {
    name: "정복",
    level: 25,
    personCount: 9,
    discription:
      "활발한 플레이를 지향하는 길드입니다. 가입 문의는 parkflexible",
    guildImage: null,
    guildMaster: "parkflexible",
    guildSubMaster: "gasanzom",
    guildMember: [
      "skyandme",
      "dksgusdn61",
      "cugar",
      "hhhello0507",
      "skwo27",
      "ganggun",
      "tumblecat44",
    ],
    createdAt: "2025. 11. 03.",
    rank: 3,
    condition: "레벨 90 이상",
    contact: "디스코드 : https://discord.gg/3cDfDtgQEg",
  },
  {
    name: "별",
    level: 43,
    personCount: 9,
    discription:
      "랭커 길드입니다. 통합레벨 120 이상만 받아요. 디스코드 필수입니다.",
    guildImage: null,
    guildMaster: "botchi",
    guildSubMaster: "ryo",
    guildMember: [
      "kita",
      "Ikuyo",
      "Yamada",
      "hitori",
      "Gotoh",
      "Nijika",
      "Kikuri",
    ],
    createdAt: "2025. 02. 27.",
    rank: 1,
    condition: "통합 레벨 120 이상",
    contact: "디스코드 : https://discord.gg/3cDfDtgQEg",
  },
  {
    name: "파도",
    level: 17,
    personCount: 12,
    discription: "소통 위주의 길드! 누구나 환영입니다.",
    guildImage: null,
    guildMaster: "waveleader",
    guildSubMaster: "surfer42",
    guildMember: ["bluefin", "seastar", "coral99", "deepdive"],
    createdAt: "2025. 04. 10.",
    rank: 45,
    condition: "무관",
    contact: "디스코드 : https://discord.gg/waveguild",
  },
  {
    name: "야성",
    level: 32,
    personCount: 25,
    discription: "매일 출석 & 레이드 참여 필수!",
    guildImage: null,
    guildMaster: "wildhunter",
    guildSubMaster: "naturecall",
    guildMember: ["lion", "tigeress", "wolfman", "bearpaw"],
    createdAt: "2024. 12. 08.",
    rank: 12,
    condition: "레벨 70 이상",
    contact: "디스코드 : https://discord.gg/wildclan",
  },
  {
    name: "초신성",
    level: 50,
    personCount: 40,
    discription: "최정상 랭커들이 모인 곳. 매주 경쟁전 필참.",
    guildImage: null,
    guildMaster: "stellarcore",
    guildSubMaster: "nova_x",
    guildMember: ["sirius", "vega", "altair", "proxima"],
    createdAt: "2023. 07. 15.",
    rank: 2,
    condition: "통합 레벨 130 이상",
    contact: "디스코드 : https://discord.gg/supernova",
  },
  {
    name: "은하수",
    level: 28,
    personCount: 19,
    discription: "편안한 분위기에서 함께 즐겨요 🌌",
    guildImage: null,
    guildMaster: "milkyway",
    guildSubMaster: "starlight",
    guildMember: ["moonbean", "galaxian", "orbiter", "telescope"],
    createdAt: "2025. 01. 03.",
    rank: 27,
    condition: "레벨 50 이상",
    contact: "디스코드 : https://discord.gg/galaxy",
  },
  {
    name: "낙원",
    level: 15,
    personCount: 8,
    discription: "힐링을 원하는 유저들 모여라~",
    guildImage: null,
    guildMaster: "paradise",
    guildSubMaster: "relaxman",
    guildMember: ["sunny", "peacecat", "lemontea", "plumeria"],
    createdAt: "2025. 06. 12.",
    rank: 67,
    condition: "무관",
    contact: "디스코드 : https://discord.gg/heavenlyplace",
  },
  {
    name: "철혈",
    level: 39,
    personCount: 35,
    discription: "매주 전투 및 길드전 중심의 하드코어 길드",
    guildImage: null,
    guildMaster: "ironclad",
    guildSubMaster: "steelwing",
    guildMember: ["blade123", "armor_kid", "warriorx", "bullet"],
    createdAt: "2025. 03. 20.",
    rank: 4,
    condition: "레벨 100 이상",
    contact: "디스코드 : https://discord.gg/bloodandiron",
  },
  {
    name: "스프링필드",
    level: 11,
    personCount: 6,
    discription: "가볍게 즐기는 친목 중심 길드입니다 🌸",
    guildImage: null,
    guildMaster: "homerun23",
    guildSubMaster: "marge87",
    guildMember: ["lisa", "bart", "maggie", "nedflanders"],
    createdAt: "2025. 05. 05.",
    rank: 101,
    condition: "무관",
    contact: "디스코드 : https://discord.gg/springfield",
  },
  {
    name: "어비스",
    level: 48,
    personCount: 33,
    discription: "심연의 전사들이 모인 길드. 컨텐츠 올클 기준.",
    guildImage: null,
    guildMaster: "darklord",
    guildSubMaster: "abysswalker",
    guildMember: ["shade", "voidy", "tentacle", "oblivion"],
    createdAt: "2024. 11. 30.",
    rank: 6,
    condition: "통합 레벨 110 이상",
    contact: "디스코드 : https://di",
  },
];
